cart/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern
from . import views

app_name='cart'

urlpatterns = [
    path('add/<uuid:product_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<uuid:product_id>/', views.cart_remove, name='cart_remove'),
    path('full_remove/<uuid:product_id>/', views.full_remove, name='full_remove')
]

order/urls.py
from django.urls import path
from order import views 
from .views import orderHistory, orderDetail

app_name='order'

urlpatterns = [
    path('thanks/<int:order_id>/', views.thanks, name='thanks'),
    path('history/', orderHistory.as_view(), name= 'order_history'),
    path('<int:order_id>/', orderDetail.as_view(), name='order_detail'),
]

search_app/urls.py
from django.urls import path
from .views import SearchResultsListView

app_name = 'search_app'

urlpatterns = [
   path('', SearchResultsListView.as_view(), name='searchResult'),
   
]

shop/urls.py
from django.urls import path
from .views import ProdCat, ProdDetail
app_name = 'shop'

urlpatterns = [
    path('', ProdCat.as_view(), name= 'allProdCat'),
    path('<uuid:category_id>/', ProdCat.as_view(), name= 'products_by_category'),
    path('<uuid:category_id>/<uuid:product_id>/', ProdDetail.as_view(), name= 'prod_detail'),
]

shop_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('pages.urls')),
    path('', include('shop.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('search/', include('search_app.urls')),
    path('vouchers/', include('vouchers.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <title>CA2</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.0/font/bootstrap-icons.css" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"></script>
</head>

<body>
    {% include 'navbar.html' %}
    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>

    {% include 'footer.html' %}
    {% block javascript %}
    <script src="{% static 'js/base.js' %}"></script>
    {% endblock javascript %}
</body>

</html>

templates/footer.html
<div>
    <footer class="bg-dark text-center text-white ">
        <div class="container p-3">
            <section class="m-5">
                <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><span
                        class="bi-facebook"></span></a>
                <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><span
                        class="bi-twitter"></span></a>
                <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><span
                        class="bi-instagram"></span></a>
                </a>
            </section>
            <p>&copy; Online Games Store. Games are property of their respective owners.</p>
        </div>

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Home{% endblock title %}
{% block content %}
<br>
<div id="demo" class="carousel slide shadow m-3 p-3" data-bs-ride="carousel">
    <div class="carousel-indicators my-8 p-2">
        <button type="button" data-bs-target="#demo" data-bs-slide-to="0" class="active"></button>
        <button type="button" data-bs-target="#demo" data-bs-slide-to="1"></button>
        <button type="button" data-bs-target="#demo" data-bs-slide-to="2"></button>
    </div>
    <div class="carousel-inner p-2" style="height: 400px">
        <div class="carousel-item active">
            <img src="static/images/switch.jpg" style="width:700px" alt="switch" class="d-block w-100">
        </div>
        <div class="carousel-item">
            <img src="static/images/ps5.jpg" alt="ps5" class="d-block w-100">
        </div>
        <div class="carousel-item">
            <img src="static/images/xbox.jpg" alt="xbox" class="d-block w-100">
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#demo" data-bs-slide="prev">
        <span class="carousel-control-prev-icon"></span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#demo" data-bs-slide="next">
        <span class="carousel-control-next-icon"></span>
    </button>
</div>


    </div>

    <div class="row">

        <div class="col-lg-4 col-md-4 col-xs-4 p-5">
            <a class="thumbnail" href="#">
                <img class="img-responsive" src="media/category/buttonswitch.png" alt="" style = "width:50%">
            </a>
        </div>
        <div class="col-lg-4 col-md-4 col-xs-4 p-5">
            <a class="thumbnail" href="#">
                <img class="img-responsive" src="media/category/ps5button.png" alt=""  style = "width:50%">
            </a>
        </div>
        <div class="col-lg-4 col-md-4 col-xs-4 p-5">
            <a class="thumbnail" href="#">
                <img class="img-responsive" src="media/category/xboxbutton.png" alt="" style = "width:50%">
            </a>
        </div>
    {% endblock content %}

templates/navbar.html
{% load static %}
<header>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}"><img id="logo"
                src="{% static 'images/logo.png' %}" alt="logo"
                draggable="false" height="60" /></a>

        <button class="navbar-toggler" type="button" data-mdb-toggle="collapse"
            data-mdb-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
            aria-label="Toggle navigation">
            <i class="fas fa-bars"></i>
        </button>
        {% if user.is_authenticated %}
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-4">
                <li class="nav-item">
                    <a class="nav-link active align-items-center" aria-current="page" href="#"><i
                            class="fas"></i>{{user.username}}</a>
                </li>
                {% endif %}
            </ul>
           
                
            <form class="d-flex" action="{% url 'search_app:searchResult' %}" mrthod="get">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q">
                <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
            </form>

            <ul class="navbar-nav ms-3">
                
                <li class="nav-item">
                    <a class="nav-link d-flex align-items-center me-3" href="{% url 'cart:cart_detail' %}"><span class="bi-cart me-2">({{item_count}})</span>  My Cart </a>
                
                    
                    {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">Shop</a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'shop:allProdCat' %}"> All Products</a></li>
                        {% for cat in links %}
                        <li><a class="dropdown-item" href="{{cat.get_absolute_url}}"> {{cat.name}}</a></li>
                        <br>
                        {% endfor %}
                    </ul>
                    {% endif %}
                    
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"><span class ="bi-person me-2"></span>My Account</a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'order:order_history' %}"><span class="bi-pencil-fill"></span> Order History</a></li>
                            <li><a class="dropdown-item" href="{% url 'signout' %}"><span class="bi-box-arrow-in-right"></span> Log out</a>
                            </li>
            </ul>
        </div>

        <div class="nav navbar-nav">
            <li class="nav-item">
                <a class="btn btn-outline-light " href="{% url 'signin' %}"><span class="bi-box-arrow-in-left"></span> Login</a>
                <li class="nav-item">
                    <a class="btn btn-outline-light" href="{% url 'signup' %}"><span class="bi-door-open"></span> Sign up</a>
            </li>
        </ul>
     
    </div>
</nav>
<div id="into-jumbotron" class="p-3 text-center text-white">
    <div class="container">
      <div class="row">
        <div class="col-lg-4 d-flex align-items-center justify-content-center border-right">
          <a href="" class="text-reset">
            <h5 class="mb-0"><span class="bi-justify"></span>Browse Around</h5>
          </a>
        </div>
        <div class="col-lg-3 border-right">
          <span>Welcome to Games Corner, your one stop shop for your gaming needs.</span>
            
        </div>
        <div class="col-lg-3 border-right">
            <span>The newest Nintendo Switch, PS5 and Xbox Series X games are available.</span>
              
          </div>
      </div>
    </div>
  </div>
  </header>